---

i3_gaps_git_path: "{{ lookup('env','HOME') }}/.cache/i3-gaps-git"
i3_gaps_git_url: https://github.com/maestrogerardo/i3-gaps-deb

i3_gaps_shared_packages:
  - i3status

i3_gaps_build_dependencies:
  - curl
  - git